### ISSUE TITLE
Add how to use this

### ISSUE THREAD

**Issue by maelle** [r-hub/rhub-server#30]
I volunteer to add instructions, using the current ones. In this issue I'm keeping track of my progress of lack thereof.

* Download a release (rather than cloning the repo?)

* Install Docker and Docker compose. I wrote `sudo install docker-compose` but there's https://docs.docker.com/compose/install/

* Run `docker-compose build` (and then wait)

**Comment by gaborcsardi** [comment]
I am not sure if the installation instructions for docker compose belong in this repo. It is bound to go stale. I think it is just enough to add a link to it.

We might need to use `docker stack deploy` in the end, anyway, and not compose.

**Comment by maelle** [comment]
* Yes I just wrote I didn't follow the installation instructions to remember I didn't.

* So I shouldn't use `docker-compose build`?

**Comment by gaborcsardi** [comment]
> So I shouldn't use docker-compose build?

You can, for now. It is `docker-compose up` I believe.

**Comment by maelle** [comment]
Current error

```
ERROR: for rhubserver09_backend_1  ('Connection aborted.', error(13, 'Permission denied'))

ERROR: for rhubserver09_frontend_1  ('Connection aborted.', error(13, 'Permission denied'))

ERROR: for rhubserver09_logdb-seed_1  ('Connection aborted.', error(13, 'Permission denied'))

ERROR: for logdb-seed  ('Connection aborted.', error(13, 'Permission denied'))

ERROR: for frontend  ('Connection aborted.', error(13, 'Permission denied'))

ERROR: for backend  ('Connection aborted.', error(13, 'Permission denied'))
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

```

**Comment by gaborcsardi** [comment]
Is Docker running properly?

**Comment by maelle** [comment]
I haven't explicitly started it indeed :grimacing:

**Comment by maelle** [comment]
Well I googled my error message and it turned out I need to use `sudo`. Now I have a different error message to google.

```
(base) maelle@maelle:~/Documents/R-hub/rhub-server-0.9$ sudo docker-compose up
Starting rhubserver09_linux-builder_1 ... 
Starting rhubserver09_cron_1 ... 
Starting rhubserver09_cron_1
Starting rhubserver09_linux-builder_1
Starting rhubserver09_jenkins_1 ... 
Starting rhubserver09_logdb_1 ... 
Starting rhubserver09_logdb_1
Starting rhubserver09_jenkins_1
Starting rhubserver09_redis_1 ... 
Starting rhubserver09_redis_1
Starting rhubserver09_queue_1 ... 
Starting rhubserver09_queue_1

ERROR: for rhubserver09_logdb_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for rhubserver09_queue_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for rhubserver09_linux-builder_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for rhubserver09_cron_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for rhubserver09_redis_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for rhubserver09_jenkins_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for linux-builder  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for logdb  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for cron  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for redis  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for queue  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for jenkins  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

**Comment by maelle** [comment]
I need to find out by what the address is used, after a restart I get

```
(base) maelle@maelle:~/Documents/R-hub/rhub-server-0.9$ sudo docker-compose up
[sudo] password for maelle: 
Starting rhubserver09_linux-builder_1 ... 
Starting rhubserver09_linux-builder_1
Starting rhubserver09_cron_1 ... 
Starting rhubserver09_jenkins_1 ... 
Starting rhubserver09_logdb_1 ... 
Starting rhubserver09_cron_1
Starting rhubserver09_jenkins_1
Starting rhubserver09_redis_1 ... 
Starting rhubserver09_queue_1 ... 
Starting rhubserver09_queue_1
Starting rhubserver09_redis_1
Starting rhubserver09_queue_1 ... done
Starting rhubserver09_linux-builder_1 ... done
Starting rhubserver09_logdb_1 ... done
Starting rhubserver09_frontend_1 ... 
Starting rhubserver09_logdb-seed_1 ... 
Starting rhubserver09_logdb-seed_1
Starting rhubserver09_frontend_1 ... done
Starting rhubserver09_nginx_1 ... 
Starting rhubserver09_nginx_1 ... error

ERROR: for rhubserver09_nginx_1  Cannot start service nginx: driver failed programming external connectivity on endpoint rhubserver09_nginx_1 (f9f53296d73a605b138a777c40ae32db865987c4e9602e634a44c8162e9315a5): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint rhubserver09_nginx_1 (f9f53296d73a605b138a777c40ae32db865987c4e9602e634a44c8162e9315a5): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

**Comment by maelle** [comment]
I made this edit

```
   nginx:
     build: ./nginx
     volumes:
     - artifacts-data:/artifacts:ro
     ports:
     - "8084:80"
```

**Comment by maelle** [comment]
Current error

```
frontend_1       | Error: Cannot find module 'r-constants'
frontend_1       |     at Function.Module._resolveFilename (module.js:548:15)
frontend_1       |     at Function.Module._load (module.js:475:25)
frontend_1       |     at Module.require (module.js:597:17)
frontend_1       |     at require (internal/module.js:11:18)
frontend_1       |     at Object.<anonymous> (/usr/src/app/node_modules/rdesc-parser/index.js:1:74)
frontend_1       |     at Module._compile (module.js:653:30)
frontend_1       |     at Object.Module._extensions..js (module.js:664:10)
frontend_1       |     at Module.load (module.js:566:32)
frontend_1       |     at tryModuleLoad (module.js:506:12)
frontend_1       |     at Function.Module._load (module.js:498:3)
frontend_1       | npm ERR! code ELIFECYCLE
frontend_1       | npm ERR! errno 1
frontend_1       | npm ERR! rhub-frontend@0.0.0 start: `node ./bin/www`
frontend_1       | npm ERR! Exit status 1
frontend_1       | npm ERR! 
frontend_1       | npm ERR! Failed at the rhub-frontend@0.0.0 start script.
frontend_1       | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
frontend_1       | 
frontend_1       | npm ERR! A complete log of this run can be found in:
frontend_1       | npm ERR!     /root/.npm/_logs/2020-02-11T16_15_40_489Z-debug.log
nginx_1          | Operation timed out

```

**Comment by maelle** [comment]
Does this mean I should somehow install https://github.com/r-hub/r-constants?

**Comment by maelle** [comment]
and before that I haves many errors like

```
logdb_1          | [notice] 2020-02-11T16:00:22.598212Z nonode@nohost <0.345.0> -------- chttpd_auth_cache changes listener died database_does_not_exist at mem3_shards:load_shards_from_db/6(line:395) <= mem3_shards:load_shards_from_disk/1(line:370) <= mem3_shards:load_shards_from_disk/2(line:399) <= mem3_shards:for_docid/3(line:86) <= fabric_doc_open:go/3(line:38) <= chttpd_auth_cache:ensure_auth_ddoc_exists/2(line:187) <= chttpd_auth_cache:listen_for_changes/1(line:134)
logdb_1          | [error] 2020-02-11T16:00:22.598330Z nonode@nohost emulator -------- Error in process <0.8384.0> with exit value:
logdb_1          | {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,395}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,370}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,399}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,86}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,38}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,187}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,134}]}]}
logdb_1          | 
```

**Comment by maelle** [comment]
Reg r-constants, I opened https://github.com/r-hub/r-constants/pull/1/files, but I have no idea whether it's linked.

**Comment by maelle** [comment]
Well https://www.npmjs.com/package/r-constants if npm tries to use the repository (I don't know how npm works) it won't work

**Comment by 2005m** [comment]
Hi,
Is the purpose of this issue to document how to run rhub locally on a server/computer? I am interested in learning how rhub works and is built. Is there any documentation?
I would eventually be interested to contribute if I can...
Thank you

**Comment by gaborcsardi** [comment]
> https://docs.r-hub.io/technical/

Some: https://docs.r-hub.io/technical/
